"""lingpai-department

Revision ID: 6ef212fc4150
Revises: f93f7fa8cb2c
Create Date: 2019-05-10 15:57:10.851145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ef212fc4150'
down_revision = 'f93f7fa8cb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lingpai', sa.Column('department', sa.String(length=255), nullable=True))
    op.drop_column('lingpai', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lingpai', sa.Column('subject', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('lingpai', 'department')
    # ### end Alembic commands ###
