"""init

Revision ID: 827c9500698d
Revises: 
Create Date: 2019-04-26 18:05:14.505053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827c9500698d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('current_process_timeout', sa.Float(), nullable=True))
    op.add_column('business', sa.Column('current_process_used_time', sa.Float(), nullable=True))
    op.add_column('step', sa.Column('timeout', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step', 'timeout')
    op.drop_column('business', 'current_process_used_time')
    op.drop_column('business', 'current_process_timeout')
    # ### end Alembic commands ###
