"""used_time

Revision ID: 8ec757ba7422
Revises: 827c9500698d
Create Date: 2019-04-28 10:03:06.028367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ec757ba7422'
down_revision = '827c9500698d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('current_process_start_time', sa.DateTime(), nullable=True))
    op.add_column('business', sa.Column('takan_used_time', sa.Float(), nullable=True))
    op.drop_column('business', 'used_time')
    op.drop_column('business', 'current_process_used_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('current_process_used_time', mysql.FLOAT(), nullable=True))
    op.add_column('business', sa.Column('used_time', mysql.FLOAT(), nullable=True))
    op.drop_column('business', 'takan_used_time')
    op.drop_column('business', 'current_process_start_time')
    # ### end Alembic commands ###
