"""role_add_field

Revision ID: a015ac4b6098
Revises: e58067695c5d
Create Date: 2019-05-10 17:14:44.084055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a015ac4b6098'
down_revision = 'e58067695c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission_check', sa.String(length=128), nullable=True))
    op.drop_column('role', 'permissoin_check')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissoin_check', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('role', 'permission_check')
    # ### end Alembic commands ###
