"""role_add_field

Revision ID: e58067695c5d
Revises: 6ef212fc4150
Create Date: 2019-05-10 17:08:22.271358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58067695c5d'
down_revision = '6ef212fc4150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission_half_check', sa.String(length=128), nullable=True))
    op.add_column('role', sa.Column('permissoin_check', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissoin_check')
    op.drop_column('role', 'permission_half_check')
    # ### end Alembic commands ###
